# Example 2
#
# Single box with VirtualBox provider.
#
# NOTE: Make sure you have the ubuntu/trusty64 base box installed...
# vagrant box add ubuntu/trusty64 http://files.vagrantup.com/ubuntu/trusty64.box
#
# VirtualBox modifyvm docs: http://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm

Vagrant.configure("2") do |config|
  config.vm.box = "lasp/ubuntu18.04"
  config.vm.hostname = "ubuntu.box"
  config.vm.network :private_network, ip: "172.22.101.11"

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--cpuexecutioncap", "50",
      "--memory", "256",
    ]
  end
end
