# Example 1
#
# Single box with some custom configuration.
#
# NOTE: Make sure you have the ubuntu/trusty64 base box installed...
# vagrant box add ubuntu/trusty64 http://files.vagrantup.com/ubuntu/trusty64.box

val1 = ENV['VAL1']
puts "------------------------------"
puts "Usage : VAL1=abcd vagrant up"
puts  "#{val1} length is #{val1.to_s.length}"
puts "------------------------------"


Vagrant.configure("2") do |config|
  config.vm.box = "lasp/ubuntu18.04"
  config.vm.hostname = "ubuntu.box"
  config.vm.network :private_network, ip: "172.3.4.11"
end
