# Example 1
#
# Single box with some custom configuration.
#
# NOTE: Make sure you have the ubuntu/trusty64 base box installed...
# vagrant box add ubuntu/trusty64 http://files.vagrantup.com/ubuntu/trusty64.box

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION ) do |config|
  config.vm.box = "lasp/ubuntu18.04"
  config.vm.hostname = "ubuntu.box"
  config.vm.network :private_network, ip: "172.3.4.11"
  config.vm.provision "shell", path: "./vagrant/vmhost.sh", args: ""

end
