# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.provider 'virtualbox' do |vb|
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
  end  

  # nowage Changed
  #config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp: false

  $num_instances = 1
  (1..$num_instances).each do |i|
    config.vm.define "h#{i}" do |node|
    # boxes at https://vagrantcloud.com/search.
    #node.vm.box = "lasp/ubuntu18.04"
    #node.vm.box = "bento/ubuntu-18.04"
    node.vm.box = "generic/ubuntu1804"
    node.vm.hostname = "h#{i}"
    ip = "172.17.8.#{i+99}"
    node.vm.network "private_network", ip: ip
    #node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    # node.vm.network "public_network"

    node.vm.provider "virtualbox" do |vb|
      # vb.gui = true
      vb.name="h#{i}"
      vb.cpus = 1
      vb.memory = "2048"
      end
      # config.vm.provision "shell", inline: <<-SHELL
      #   apt-get update
      #   apt-get install -y apache2
      # SHELL
      node.vm.provision "shell", path: "install.sh", args:[i]
    end  
  end
end
